import { Profile, Education, Skill, Project } from '../types';

export const initialProfile: Profile = {
  id: '1',
  name: 'Gilang Surya Ramadhan',
  title_id: 'Gilang Surya Ramadhan - Specialist Programmer',
  title_en: 'Gilang Surya Ramadhan - Specialist Programmer',
  tagline_id: 'Bersemangat dalam bidang teknologi, selalu mengikuti perkembangan terbaru dan berusaha memberikan solusi terbaik melalui pemrograman.',
  tagline_en: 'Passionate about technology, always keeping up with the latest developments and striving to provide the best solutions through programming.',
  about_id: 'Saya adalah seorang siswa SMK Telkom Purwokerto, saya saat ini merupakan seorang siswa kelas 11. Di SMK Telkom Purwokerto saya belajar berbagai hal yang berkaitan dengan teknologi seperti mengembangkan website, aplikasi, dan mempelajari tentang machine learning. Pernah membuat website menggunakan HTML, CSS, dan JavaScript, serta mempelajari Laravel.',
  about_en: 'I am a student at SMK Telkom Purwokerto, currently in 11th grade. At SMK Telkom Purwokerto, I learn various things related to technology such as developing websites, applications, and studying machine learning. I have created websites using HTML, CSS, and JavaScript, and have also studied Laravel.',
  avatar_url: '/img/optimized/gw.webp',
  logo_url: '/img/optimized/gw-bunder.webp',
  cv_url: '/assests/CV.pdf',
  email: 'gilangsuryaramadhan10@gmail.com',
  github_url: 'https://github.com/gilangsuryaa',
  linkedin_url: 'https://www.linkedin.com/in/gilang-surya-ramadhan-781084391',
  instagram_url: 'https://www.instagram.com/gilang.sra',
  location: 'Purwokerto, Indonesia',
  specialization: 'Rekayasa Perangkat Lunak',
  current_school: 'SMK Telkom',
  school_period: '2024 - 2027',
  specialization_1: 'Frontend & Web',
  specialization_2: 'Next.js & Laravel',
  specialization_3: 'Supabase & SQL',
  philosophy_id: 'Membangun aplikasi yang cepat, bersih, dan berorientasi pengguna.',
  philosophy_en: 'Building fast, clean, and user-centric applications.',
  philosophy_desc_id: 'Selalu antusias mempelajari teknologi terdepan dan menyajikan arsitektur kode yang terstruktur.',
  philosophy_desc_en: 'Passionate about exploring modern web technologies and engineering well-architected solutions.',
  motto: 'Clean Code & Architecture',
};

export const initialEducation: Education[] = [
  {
    id: 'edu-1',
    institution: 'SD Negeri 2 Losari Kidul',
    period: '2015-2021',
    description_id: 'Pernah menempuh pendidikan dasar di SD Negeri 2 Losari Kidul',
    description_en: 'Completed elementary education at SD Negeri 2 Losari Kidul',
    order_index: 1,
  },
  {
    id: 'edu-2',
    institution: 'SMP Negeri 1 Losari',
    period: '2021-2024',
    description_id: 'Pernah menempuh pendidikan menengah tingkat awal di SMP Negeri 1 Losari',
    description_en: 'Completed junior high school education at SMP Negeri 1 Losari',
    order_index: 2,
  },
  {
    id: 'edu-3',
    institution: 'SMK Telkom Purwokerto',
    period: '2024-2027',
    description_id: 'Sedang menempuh pendidikan menengah di SMK Telkom Purwokerto, jurusan Rekayasa Perangkat Lunak dengan fokus pengembangan web.',
    description_en: 'Currently pursuing vocational education at SMK Telkom Purwokerto, majoring in Software Engineering with a focus on web development.',
    order_index: 3,
  },
];

export const initialSkills: Skill[] = [
  { id: 'skill-1', name: 'Figma', icon_url: 'https://skillicons.dev/icons?i=figma', category: 'Design', order_index: 1 },
  { id: 'skill-2', name: 'HTML5', icon_url: 'https://skillicons.dev/icons?i=html', category: 'Frontend', order_index: 2 },
  { id: 'skill-3', name: 'CSS3', icon_url: 'https://skillicons.dev/icons?i=css', category: 'Frontend', order_index: 3 },
  { id: 'skill-4', name: 'JavaScript', icon_url: 'https://skillicons.dev/icons?i=js', category: 'Frontend', order_index: 4 },
  { id: 'skill-5', name: 'PHP', icon_url: 'https://skillicons.dev/icons?i=php', category: 'Backend', order_index: 5 },
  { id: 'skill-6', name: 'MySQL', icon_url: 'https://skillicons.dev/icons?i=mysql', category: 'Database', order_index: 6 },
  { id: 'skill-7', name: 'Git', icon_url: 'https://skillicons.dev/icons?i=git', category: 'Tools', order_index: 7 },
  { id: 'skill-8', name: 'Python', icon_url: 'https://skillicons.dev/icons?i=python', category: 'Language', order_index: 8 },
];

export const initialProjects: Project[] = [
  {
    id: 'proj-1',
    slug: 'cronela',
    title: 'CRONELA',
    category_id: 'Website Pendidikan',
    category_en: 'Education Website',
    description_id: 'Mengembangkan situs web pembelajaran daring menggunakan HTML, CSS, dan JavaScript, terintegrasi dengan video YouTube dan fitur interaktif untuk melibatkan pengguna.',
    description_en: 'Developing an online learning website using HTML, CSS, and JavaScript, integrated with YouTube videos and interactive features to engage users.',
    cover_image: '/img/optimized/cronela/home.webp',
    overview_id: 'Saya dan tim mengembangkan sebuah website pendidikan online yang berisi video-video pembelajaran dan juga kuis interaktif.',
    overview_en: 'My team and I developed an online education website featuring learning videos and interactive quizzes.',
    role_id: 'Fullstack Developer',
    role_en: 'Fullstack Developer',
    tools: 'PHP, CSS, JS, MySQL',
    timeline_id: '3 Bulan',
    timeline_en: '3 Months',
    process_id: 'Proses pembuatan diawali dengan mencari ide website yang akan berguna bagi banyak orang. Jadi kami membuat website pendidikan, yang di dalamnya berisikan video-video pendidikan dan juga berisi kuis interaktif yang dapat menguji kemampuan pengguna.',
    process_en: 'The development process began by brainstorming website ideas beneficial to many. We created an education website with instructional videos and interactive quizzes to test user skills.',
    challenge_id: 'Bagian yang cukup menantang dari projek ini adalah ketika membuat section register dan login, selain itu, membuat bagian kuis agar bisa menyimpan skor user juga merupakan tugas yang cukup menantang.',
    challenge_en: 'A challenging part of this project was implementing the register and login section, along with creating the quiz component to reliably store user scores.',
    challenge_images: [
      '/img/optimized/cronela/login.webp',
      '/img/optimized/cronela/quiz.webp',
    ],
    github_url: 'https://github.com/gilangsuryaa/Cronela',
    live_url: '',
    order_index: 1,
    featured: true,
  },
  {
    id: 'proj-2',
    slug: 'vashion',
    title: 'VASHION',
    category_id: 'Website Ecommerce',
    category_en: 'Ecommerce Website',
    description_id: 'Mengembangkan platform belanja pakaian daring yang memanfaatkan komponen pengembangan web fundamental seperti HTML, CSS, dan JavaScript, terintegrasi dengan database menggunakan SQL dan PHP.',
    description_en: 'Developing an online clothing shopping platform utilizing fundamental web development components such as HTML, CSS, and JavaScript, integrated with a database using SQL and PHP.',
    cover_image: '/img/optimized/vashion/home.webp',
    overview_id: 'Saya dan tim mengembangkan sebuah website ecommerce pakaian online yang memungkinkan pengguna untuk mencari, melihat, dan membeli pakaian dengan mudah.',
    overview_en: 'My team and I developed an online clothing ecommerce website allowing users to search, view, and purchase apparel seamlessly.',
    role_id: 'Frontend & Database Developer',
    role_en: 'Frontend & Database Developer',
    tools: 'PHP, HTML, CSS, JS, MySQL',
    timeline_id: '2 Bulan',
    timeline_en: '2 Months',
    process_id: 'Perancangan desain UI/UX di Figma, kemudian mengimplementasikannya ke HTML/CSS serta menghubungkan katalog produk dengan database MySQL menggunakan backend PHP.',
    process_en: 'Designed UI/UX in Figma, then implemented it into HTML/CSS and connected product catalogs to a MySQL database using PHP backend.',
    challenge_id: 'Membangun logika keranjang belanja dan manajemen inventaris stok produk yang responsif secara real-time.',
    challenge_en: 'Building the shopping cart logic and inventory stock management that responds in real-time.',
    challenge_images: [
      '/img/optimized/vashion/home.webp',
    ],
    github_url: 'https://github.com/gilangsuryaa',
    live_url: '',
    order_index: 2,
    featured: true,
  },
  {
    id: 'proj-3',
    slug: 'portfolio',
    title: 'Website Portofolio',
    category_id: 'Personal Website',
    category_en: 'Personal Website',
    description_id: 'Mengembangkan website portfolio yang berisi informasi tentang diri saya, dan projek-projek yang pernah saya buat dengan menggunakan HTML, CSS, dan JavaScript.',
    description_en: 'Developing a portfolio website that contains information about myself and the projects I have created using HTML, CSS and JavaScript.',
    cover_image: '/img/optimized/portfolio/home.webp',
    overview_id: 'Website portofolio interaktif untuk menampilkan karya, profil, skill, dan studi kasus pengembangan web.',
    overview_en: 'An interactive portfolio website to showcase work, profile, skills, and web development case studies.',
    role_id: 'Solo Developer & Designer',
    role_en: 'Solo Developer & Designer',
    tools: 'Next.js, Tailwind CSS, TypeScript, Supabase',
    timeline_id: '1 Bulan',
    timeline_en: '1 Month',
    process_id: 'Merancang arsitektur web modern berbasis Next.js, membuat sistem tema gelap/terang, multi-bahasa, serta integrasi CMS Supabase untuk kemudahan update konten.',
    process_en: 'Architected modern Next.js web application, implemented dark/light theme, bilingual support, and Supabase CMS integration for effortless content management.',
    challenge_id: 'Menyusun CMS admin yang aman dan mudah digunakan tanpa mengorbankan performa kecepatan loading website publik.',
    challenge_en: 'Structuring a secure, user-friendly CMS dashboard while maintaining optimal public loading performance.',
    challenge_images: [
      '/img/optimized/portfolio/home.webp',
    ],
    github_url: 'https://github.com/gilangsuryaa',
    live_url: '',
    order_index: 3,
    featured: true,
  },
  {
    id: 'proj-4',
    slug: 'mycelengan',
    title: 'My Celengan',
    category_id: 'Aplikasi Android Mobile',
    category_en: 'Android Mobile App',
    description_id: 'Mengembangkan aplikasi mobile android berbasis kotlin yang berfungsi untuk mencatat pengeluaran dan pemasukan pengguna, serta dengan fitur target agar pengguna termotivasi untuk menabung.',
    description_en: 'Developing a Kotlin-based Android mobile application that functions to record user expenses and income, as well as with a target feature to motivate users to save.',
    cover_image: '/img/optimized/mycelengan/splashscreen.webp',
    overview_id: 'Aplikasi pencatatan keuangan pribadi dengan fitur manajemen tabungan dan target finansial.',
    overview_en: 'A personal finance tracking app featuring savings management and financial goals.',
    role_id: 'Android Developer',
    role_en: 'Android Developer',
    tools: 'Kotlin, Android Studio, SQLite / Room',
    timeline_id: '2 Bulan',
    timeline_en: '2 Months',
    process_id: 'Membangun antarmuka mobile yang ramah pengguna menggunakan Kotlin, mengimplementasikan Room Database lokal, dan visualisasi grafik pemasukan/pengeluaran.',
    process_en: 'Built a user-friendly mobile UI using Kotlin, implemented local Room Database, and income/expense visual charts.',
    challenge_id: 'Mengatur alur perhitungan transaksi dan kalkulasi progres target tabungan secara akurat dan konsisten.',
    challenge_en: 'Handling transaction calculation flows and savings target progress tracking accurately and consistently.',
    challenge_images: [
      '/img/optimized/mycelengan/splashscreen.webp',
    ],
    github_url: 'https://github.com/gilangsuryaa',
    live_url: '',
    order_index: 4,
    featured: true,
  },
];
